version: '3'

services:
  web:
    container_name: nodeapi
    restart: always
    build: .
    ports:
      - "5000:3000"
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"